# This file was generated by GoReleaser. DO NOT EDIT.
cask "vaultcreds" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "9bc59b3ec7d9330a4048eb5700c73abe682cf5bad09f736ea043c7de88f426f4"
      url "https://github.com/freakinhippie/vault-aws-cli-credentials-go/releases/download/v#{version}/vaultcreds_#{version}_darwin_x86_64.zip"
    end
    on_arm do
      sha256 "9302d8f51ef6edecb3717f235907ff89bf1f57940fd605a0d614d01758739e45"
      url "https://github.com/freakinhippie/vault-aws-cli-credentials-go/releases/download/v#{version}/vaultcreds_#{version}_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "c3f662fbc19bb86110cb31916cbfcdc8f5156dbb50840874620cbec2cf85d7c3"
      url "https://github.com/freakinhippie/vault-aws-cli-credentials-go/releases/download/v#{version}/vaultcreds_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "9d0ea64f3208e4f7d44a4b6ddd95d45a8a4b83a2f3fc78a1499f003423ca9597"
      url "https://github.com/freakinhippie/vault-aws-cli-credentials-go/releases/download/v#{version}/vaultcreds_#{version}_linux_arm64.tar.gz"
    end
  end

  name "vaultcreds"
  desc "Vault AWS CLI/SDK external credential process helper"
  homepage "https://github.com/freakinhippie/vault-aws-cli-credentials-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vaultcreds"

  # No zap stanza required

end
