# This file was generated by GoReleaser. DO NOT EDIT.
cask "vaultcreds" do
  name "vaultcreds"
  desc "Vault AWS CLI/SDK external credential process helper"
  homepage "https://github.com/freakinhippie/vault-aws-cli-credentials-go"
  version "0.2.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vaultcreds"

  on_macos do
    on_intel do
      url "https://github.com/freakinhippie/vault-aws-cli-credentials-go/releases/download/v#{version}/vaultcreds_#{version}_darwin_x86_64.tar.gz"
      sha256 "07541cd17bbf78b0b8c0513a2682423e7f5cdcdf41c8b7529ec757a71b129f4b"
    end
    on_arm do
      url "https://github.com/freakinhippie/vault-aws-cli-credentials-go/releases/download/v#{version}/vaultcreds_#{version}_darwin_arm64.tar.gz"
      sha256 "8d270554fd7d8ccc7946534924a5c35a7f0495cc8ff2ead85e9cb90855a5c65d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/freakinhippie/vault-aws-cli-credentials-go/releases/download/v#{version}/vaultcreds_#{version}_linux_x86_64.tar.gz"
      sha256 "5cffd6152038565f8c0f0af7a037860b9631d66ef92fc8b83b396584d372751c"
    end
    on_arm do
      url "https://github.com/freakinhippie/vault-aws-cli-credentials-go/releases/download/v#{version}/vaultcreds_#{version}_linux_arm64.tar.gz"
      sha256 "a15a7ececb51824f2d7cd93c3b2775ba4253815054ee2a02fb1dc90aae6a969a"
    end
  end

  # No zap stanza required
end
